apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: axonrh-dev

resources:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - patches/resources.yaml

configMapGenerator:
  - name: axonrh-config
    behavior: merge
    literals:
      - SPRING_PROFILES_ACTIVE=dev,kubernetes
      - LOG_LEVEL=DEBUG
