apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: axonrh

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.yaml
  - postgres-deployment.yaml
  - redis-deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: axonrh

commonAnnotations:
  app.kubernetes.io/version: "1.0.0"
